name: hello

on:
  push:
    branches:
      - master

jobs:
  hello_job:
    runs-on: ubuntu-20.04
    steps:
      - name: echo hello
        run: |
          echo "hello"

      - name: print date
        run: date

      - name: print working directory
        run: ls
